### ISSUE TITLE
PostBarcodeRecognizeFromUrlOrContent fails when passing image stream

### ISSUE THREAD

**Issue by ronmichael** [aspose-barcode-cloud/aspose-barcode-cloud-dotnet#31]
PostBarcodeRecognizeFromUrlOrContent works if I pass a URL but fails with this error if I pass an image stream:

`The 'Content-Type' header must be modified using the appropriate property or method.
Parameter name: name`

I haven't been able to dig down through the code far enough yet to figure out the solution.

**Comment by Denis-Averin** [comment]
Please check release #34 it should be fixed
